[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=/usr/bin/loginctl poweroff
Numlock=on
RebootCommand=/usr/bin/loginctl reboot

[Theme]
Current=breeze
CursorTheme=breeze_cursors
Font=Noto Sans,10,-1,0,400,0,0,0,0,0,0,0,0,0,0,1,,0,0

[Users]
MaximumUid=60513
MinimumUid=1000
